# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_listar.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests, json
from zeep import Client

class Ui_Listar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 675)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(20, 160, 531, 481))
        self.tableView.setObjectName("tableView")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 20, 291, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_buscarID = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_buscarID.setObjectName("lbl_buscarID")
        self.gridLayout.addWidget(self.lbl_buscarID, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.btn_listarTodos = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_listarTodos.sizePolicy().hasHeightForWidth())
        self.btn_listarTodos.setSizePolicy(sizePolicy)
        self.btn_listarTodos.setObjectName("btn_listarTodos")
        self.gridLayout.addWidget(self.btn_listarTodos, 3, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.lbl_listado = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_listado.setFont(font)
        self.lbl_listado.setObjectName("lbl_listado")
        self.gridLayout.addWidget(self.lbl_listado, 1, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.spn_id = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spn_id.sizePolicy().hasHeightForWidth())
        self.spn_id.setSizePolicy(sizePolicy)
        self.spn_id.setMaximum(1000)
        self.spn_id.setObjectName("spn_id")
        self.gridLayout.addWidget(self.spn_id, 2, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(450, 40, 101, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdbtn_REST_listar = QtWidgets.QRadioButton(self.widget)
        self.rdbtn_REST_listar.setEnabled(True)
        self.rdbtn_REST_listar.setChecked(True)
        self.rdbtn_REST_listar.setObjectName("rdbtn_REST_listar")
        self.verticalLayout.addWidget(self.rdbtn_REST_listar)
        self.rdbtn_SOAP_listar = QtWidgets.QRadioButton(self.widget)
        self.rdbtn_SOAP_listar.setObjectName("rdbtn_SOAP_listar")
        self.verticalLayout.addWidget(self.rdbtn_SOAP_listar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_buscarID.setText(_translate("Dialog", "Buscar por Id:"))
        self.btn_listarTodos.setText(_translate("Dialog", "Listar todos"))
        self.lbl_listado.setText(_translate("Dialog", "Listado de Personas"))
        self.rdbtn_REST_listar.setText(_translate("Dialog", "REST"))
        self.rdbtn_SOAP_listar.setText(_translate("Dialog", "SOAP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
